# Configure environment.
language: java
jdk:
- oraclejdk8
cache:
   directories:
      - "$HOME/.m2/repository"

# Do integration test.
script: mvn verify -Dmaven.javadoc.skip=true

# Do snapshot deployment.
deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   skip_cleanup: true
   on:
      branch: develop
